### ISSUE TITLE
機能改善の要望

### ISSUE THREAD

**Issue by sakumas** [SKN-JP/Electric-Revolution#1]
いつもユニークかつ面白いゲームの開発、楽しみに拝見しています。
幾つかこうして欲しい、そして「おや？」と思うところが有りましたので、報告します。

バグ？
部品を設置後、移動する際にずれる
ずれるのは、部品の上で左クリックをホールドした際です。
1マス×1マスの部品を持ち上げるときに発生するようです。

要望
・ウィンドウが非アクティブの際は、画面をスライドしないようにしてほしい。
（画面の端にカーソルを移動させると、アクティブかどうかにかかわらず、画面内がスライドしてしまいます。）
・クッキー生産マシンの音を小さめにして欲しい

・信号を一方向にのみ通す部品を追加して欲しい（ダイオードのようなもの）
・カウンタ部品に、上の桁カウントアップ用の信号を出力させてほしい
（”F"から”０”になった時に信号を一定時間出すように）
・フリップフロップ回路、NOT回路などの論理回路も将来的にあったらいいなと思います。

**Comment by sknjpn** [comment]
・部品を設置後、移動する際にずれる
内部処理的な原因は負の座標を取るためだと考えられます。
機械の配置可能空間を限定することで対策します。

・ウィンドウが非アクティブの際は、画面をスライドしないようにしてほしい。
変更しました。

・クッキー生産マシンの音を小さめにして欲しい
Luaの効果音再生関数に音量を設定できるようにし、音量を下げました

・信号を一方向にのみ通す部品を追加して欲しい
一方方向の「特殊な」導通処理は今後の開発に響くので、採用は未定です。
短期的にはAND、NOTといった基礎回路で代用します。

・カウンタ部品に、上の桁カウントアップ用の信号を出力させてほしい
問題がなければ早期に実装します。

・フリップフロップ回路、NOT回路などの論理回路も将来的にあったらいいなと思います。
AND NAND NOT OR NOR EXOR EXNOR あたりは早期に実装します。
もしよかったら自作してみるといい経験になると思いますよ
assets/machine/カウンタ/main.lua内にカウンタのプログラムが記載されているので、
それを参考に改造してみると勉強になると思います。

Wiki内解説↓
https://github.com/SKN-JP/Electric-Revolution/wiki/%E6%A9%9F%E6%A2%B0%E3%82%92%E8%87%AA%E4%BD%9C%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by SirayamaKazuhiko** [comment]
『工場を作るゲームを作るよ！』の動画の方を拝見させてもらっています。
アイテムの輸入とゲーム内に水(水道管)を導入してもらいたいと思い、今回投稿させていただきました。

アイテムの輸入についてですが
電気により輸入の間隔を制御出来るようにして欲しいです。
理由としてはアイテムの輸入過多によるコンベアーの詰まりを改善する為です。

水道についてですが
具体的には蒸気エンジンや冷却機などに水を供給するようにしたり、
水を使った製品などの製作を出来るようにして欲しいです。
(水道を引く用のポンプなどを設けるなどなども欲しいです)

**Comment by sknjpn** [comment]
SirayamaKazuhiko さんへ

大変申し訳ございませんが、新しい報告や要望を行う場合は特定のIssueの返信ではなく、
New Issueから投稿をお願いします。
なお、今回投稿してもらった要望に対する返答はここで返信出来ないので、新しく同じ内容でIssueを投稿してください。
