### ISSUE TITLE
and演算子が0,0の時に1を返してくる

### ISSUE THREAD

**Issue by TakaSato0215** [SKN-JP/Electric-Revolution#11]
and演算子が0,0を入力されたときに1を返して来ることがあります
なぜでしょうか
![default](https://user-images.githubusercontent.com/34600386/34070679-9dce94d0-e2ad-11e7-969a-3a01621fb910.png)

**Comment by sknjpn** [comment]
よくあるパターンとして、出力が他の出力に接触しているパターンがあります。

出力に繋がっている全てのケーブルを切り離しても問題が継続する場合はバグの可能性があります。

アップデートが頻繁にされているので、最新のバージョンでまた試した上で解決しない場合はまたご報告ください。
出来れば、問題を再現する手順を書いていただけると助かります。

![20171217-004642-916](https://user-images.githubusercontent.com/29691164/34072046-c4522eee-e2c3-11e7-8220-0701b00ff909.png)
