### ISSUE TITLE
セーブ→ロード後に電源ケーブルが消える

### ISSUE THREAD

**Issue by exaexa1991** [SKN-JP/Electric-Revolution#12]
電気搬入機等から、モータなどに接続する電気ケーブルが、
セーブ→ロード後に全ての工場（確認したのは函館と苫小牧の2工場ですが…）から消えました。
私だけでしょうか。

**Comment by sknjpn** [comment]
セーブ機能にケーブルがサポートされていなかった事が原因です
今後のバージョンで修正されます
