### ISSUE TITLE
ゲーム内テクスチャーの解像度について

### ISSUE THREAD

**Issue by SK25S** [SKN-JP/Electric-Revolution#2]
ゲーム画面をズームするとPNG特有の小さい画像を伸ばしたボケが出てるのですが、ゲーム内の1マスあたりの縦と横のドット数はいくつぐらいになっているのでしょうか

**Comment by coil424** [comment]
管理者ではありませんが失礼します。
個人でいろいろを追加していってますが、1ブロック当たり16*16サイズですね。

ちなみ"config.ini"で指定できるMachineSizeは最低1*1ブロックですので8ビットのサイズのMachineを作っても現在は空白が周囲にできてしまいます。（端子類の設定とはまた別です。）

**Comment by SK25S** [comment]
標準で16×16なのですね。いろいろ試してみたところ4000×4000でもタイル1マス分の大きさに勝手に縮小されているようなので、縮小も拡大もされないサイズっていくつなんでしょう。

**Comment by SK25S** [comment]
![image](https://user-images.githubusercontent.com/20695287/31985044-a1d5923c-b99e-11e7-8c93-f21ea736f9ed.png)
こんな感じにドットの角が拡大縮小で滲んでドットのカックカク感が失われるので・・・

**Comment by sknjpn** [comment]
このゲームのシステムは1タイル当たりのドット数を明確に決めていませんが、
サンプルでは絵を書くのが楽なので16x16で素材を統一して作っています。

縮小される先のサイズはconfig.iniファイル内のsizeで決定されるので、
元の画像サイズでは決定されません。

カメラの最大倍率（マウスホイールで最も拡大した場合）は1タイルのドット数が64x64になるように設計しているので、64x64ならばスムーズな画像が作成できると思います。

ドットの雰囲気を残せるような関数については今後実装を検討しておきます。

**Comment by SK25S** [comment]
わかりました、64＾2がちょうどよいと。試しにテクスチャーを作ってみようと思っていたのでありがたいです。

**Comment by coil424** [comment]
64×2できれいに見える。
自分が作っているアイテムもリサイズしてみてみます

**Comment by SK25S** [comment]
どうやら工場のタイルは16＾2しか使えないようですね・・・
この微妙に入る縦線は何なんでしょう。
![image](https://user-images.githubusercontent.com/20695287/31988579-8c6b2f54-b9aa-11e7-9581-d63c6ada4ea6.png)

**Comment by sknjpn** [comment]
縦線は隣のチップの色が混ざった感じですね。
これはTile.pngファイルに複数のマップチップが並んで配置されていることに起因します。
これに関してはフィルタリングの設定の問題なので、次のバージョンで改善しておきます。

**Comment by SK25S** [comment]
![image](https://user-images.githubusercontent.com/20695287/31991039-bd26ff0e-b9b1-11e7-8e24-40961dbbb391.png)
64単位にするとだいぶくっきりしますね。
