### ISSUE TITLE
アイテムの輸入機構と水の実装に関する要望

### ISSUE THREAD

**Issue by SirayamaKazuhiko** [SKN-JP/Electric-Revolution#3]
『工場を作るゲームを作るよ！』の動画の方を拝見させてもらっています。
アイテムの輸入とゲーム内に水(水道管)を導入してもらいたいと思い、今回投稿させていただきました。

アイテムの輸入についてですが
電気により輸入の間隔を制御出来るようにして欲しいです。
理由としてはアイテムの輸入過多によるコンベアーの詰まりを改善する為です。

水道についてですが
具体的には蒸気エンジンや冷却機などに水を供給するようにしたり、
水を使った製品などの製作を出来るようにして欲しいです。
(水道を引く用のポンプなどを設けるなどなども欲しいです)

**Comment by sknjpn** [comment]
輸入機械の信号による制御は了解しました。近いアップデートで実装していきます。
ただし、現状でも以下のように分別コンベアを用いることによって同様の機能を実現できます。
![electric revolution 2017_10_25 22_45_53](https://user-images.githubusercontent.com/29691164/32002042-702aa352-b9d6-11e7-94fe-31785b8540dc.png)

液体パイプについてはシステムが非常に複雑になるので直ぐに実装は出来ませんが、
将来的には実装していきます。

**Comment by SirayamaKazuhiko** [comment]
返信ありがとうございます。
アップデートでの実装を楽しみにしています。
今後もゲーム制作、頑張って下さい。
