### ISSUE TITLE
ドット絵の調整について

### ISSUE THREAD

**Issue by fjsk351** [SKN-JP/Electric-Revolution#4]
動画の方楽しく拝見させていただいています。

公開中の最新版をDLしてプレイさせてもらっているのですが、
プレイする上で少し見づらいなと思うドット絵を自分で調整してプレイしています。
画像は7セグの文字が読みづらかったので調整したものです。
![7seg](https://user-images.githubusercontent.com/33113418/32037699-7704459e-ba61-11e7-8621-a20259e2c58f.jpg)
こういったものはIssuesで共有した方が良いのでしょうか？

**Comment by sknjpn** [comment]
素材提供はDropBoxなどにあげた後、Issueにリンクを投稿してもらえれば対応します。
著作権表示を望む場合はその旨をIssuesに追記してください。

**Comment by fjsk351** [comment]
ご回答いただきありがとうございます。
DropBoxを使うのが初なのでこれで合っているのかよく判りませんが上げて見たので貼っておきます。
既存の画像に手を加えただけなので著作権表示は不要です。採用の是非についてもお任せします。
https://www.dropbox.com/s/jg79kxes8cgfq55/%E5%A4%A7%E3%81%8D%E3%81%AA7%E3%82%BB%E3%82%B0.zip?dl=0

**Comment by sknjpn** [comment]
確認しました。
特に問題がなければ本体に導入させて頂きます。
提供ありがとうございました。
