### ISSUE TITLE
ICとSWのHi-Zについて

### ISSUE THREAD

**Issue by coil424** [SKN-JP/Electric-Revolution#5]
ニコニコの方で以前「Hi-Zとはなんですか？」というコメントしまして動画の方でご回答いただき有難うございます。
わからないことが出てきましたのでご質問させていただきます。

電源から7408をVccとGndにつなぎ起動させ、入力側２端子にそれぞれ電源+側よりSWを介して接続します。このとき２つSWがOFFの場合はSWからの出力はHi-Zとなります。同時にICの出力側は入力側２端子がHi-ZなのでHiと出力されてしまいます。これを正しくAND回路として動かすにはどのように配線すればよろしいでしょうか？

初心者の質問で申しわけありません。開発者様や投稿なさってる動画をご覧方々からすれば「そんな初心者の質問ここでするな。」と怒られてしまいそうですが、ご教授よろしくお願いします。

**Comment by sknjpn** [comment]
配布版とは別のバージョンですが、赤線がVCC、黒線がGND、緑線が信号線です。
押されるとHi、押されていないとHi-Zだと74シリーズは1 or 1と認識してしまいます。
なので、スイッチを使う場合、「押されるとLowを出力する」とするとよい感じに扱えます。
最も安全に簡単に扱うには下の画像のようにレバースイッチで、Hi or Lowになるように配線することです。
![electric revolution -- development version 2017_10_27 17_40_46](https://user-images.githubusercontent.com/29691164/32095394-f932af56-bb3d-11e7-9f3b-a620e02c977c.png)

実際の電子回路では「プルダウン」と呼ばれる「Hi-ZをLowにする」手法がありますが、
この世界ではそういった表現はどう頑張っても出来ないので注意が必要です。

**Comment by sknjpn** [comment]
初心者の質問はIssuesに投稿すべきではない、という話をされていましたが、
動画にQ&Aのデータを蓄積した場合視聴者にとっても、自分にとっても参照が大変なので
質問は全て管理が容易なIssuesに投稿してもらうのがベストだと考えています。

また、最終的にチュートリアルを作る際の参考になるので、
こういった初心者からの質問は貴重だと考えています。

今後の投稿の参考にしてください。

**Comment by coil424** [comment]
開発などで忙しいなか返信してくださり有難うございます。
自分の方での思い込みもあり 思うように回路を動かせませんでした。Hi-Zやプルアップ、プルダウン回路に対する知識も今回得られ 大変勉強になりました。有難うございました。
